// GENERATED by scripts/fetch-fonts.ts — do not edit by hand.
//
// Typed manifest of the bundled open-source fonts. The full license text for
// each family lives next to its files in public/fonts/<slug>/.

export type FontCategory = "sans" | "serif" | "display" | "mono";
export type FontLicense = "OFL" | "Apache-2.0";

export interface BundledFontFace {
  weight: number;
  style: "normal";
  /** Public path, e.g. /fonts/inter/Inter-Regular.ttf */
  file: string;
  /** True for variable fonts that cover the full 100–900 weight range. */
  variable?: boolean;
}

export interface BundledFont {
  family: string;
  slug: string;
  category: FontCategory;
  license: FontLicense;
  /** URL of the upstream google/fonts directory. */
  source: string;
  faces: BundledFontFace[];
}

export const BUNDLED_FONTS: BundledFont[] = [
  {
    family: "Inter",
    slug: "inter",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/inter",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/inter/Inter%5Bopsz%2Cwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Roboto",
    slug: "roboto",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/roboto",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/roboto/Roboto%5Bwdth%2Cwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Open Sans",
    slug: "opensans",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/opensans",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/opensans/OpenSans%5Bwdth%2Cwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Lato",
    slug: "lato",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/lato",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/lato/Lato-Regular.ttf" },
      { weight: 700, style: "normal", file: "/fonts/lato/Lato-Bold.ttf" },
      { weight: 600, style: "normal", file: "/fonts/lato/Lato-SemiBold.ttf" },
    ],
  },
  {
    family: "Montserrat",
    slug: "montserrat",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/montserrat",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/montserrat/Montserrat%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Poppins",
    slug: "poppins",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/poppins",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/poppins/Poppins-Regular.ttf" },
      { weight: 600, style: "normal", file: "/fonts/poppins/Poppins-SemiBold.ttf" },
      { weight: 700, style: "normal", file: "/fonts/poppins/Poppins-Bold.ttf" },
    ],
  },
  {
    family: "Work Sans",
    slug: "worksans",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/worksans",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/worksans/WorkSans%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Nunito",
    slug: "nunito",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/nunito",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/nunito/Nunito%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Raleway",
    slug: "raleway",
    category: "sans",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/raleway",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/raleway/Raleway%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Merriweather",
    slug: "merriweather",
    category: "serif",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/merriweather",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/merriweather/Merriweather%5Bopsz%2Cwdth%2Cwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Playfair Display",
    slug: "playfairdisplay",
    category: "serif",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/playfairdisplay",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/playfairdisplay/PlayfairDisplay%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Lora",
    slug: "lora",
    category: "serif",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/lora",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/lora/Lora%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Oswald",
    slug: "oswald",
    category: "display",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/oswald",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/oswald/Oswald%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Bebas Neue",
    slug: "bebasneue",
    category: "display",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/bebasneue",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/bebasneue/BebasNeue-Regular.ttf" },
    ],
  },
  {
    family: "JetBrains Mono",
    slug: "jetbrainsmono",
    category: "mono",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/jetbrainsmono",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf", variable: true },
    ],
  },
  {
    family: "Roboto Mono",
    slug: "robotomono",
    category: "mono",
    license: "OFL",
    source: "https://github.com/google/fonts/tree/main/ofl/robotomono",
    faces: [
      { weight: 400, style: "normal", file: "/fonts/robotomono/RobotoMono%5Bwght%5D.ttf", variable: true },
    ],
  },
];

/** Distinct font-family names available to the renderer/editor. */
export function fontFamilyNames(): string[] {
  return BUNDLED_FONTS.map((f) => f.family);
}
