import { test, expect } from "@playwright/test";

// One continuous journey through the whole app, recorded as a single video
// (test-results/.../video.webm): login → media upload → edit a template in the
// editor and save → use a template (fill text, pick a library image) →
// generate a real image and download → admin page.
test.describe("full journey", () => {
  test("login, media, edit template, use template, generate, admin", async ({ page }) => {
    test.setTimeout(120_000);
    page.on("dialog", (d) => d.accept());

    // 1) Logged in (storageState) — land on the dashboard.
    await page.goto("/dashboard");
    await expect(page.getByText("e2e@beeroniza.test")).toBeVisible();

    // 2) Media library — upload an image.
    await page.goto("/media");
    await page.locator('input[type="file"]').first().setInputFiles("e2e/fixtures/sample.png");
    await expect(page.getByTestId("media-tile").first()).toContainText("sample.png", { timeout: 20_000 });

    const templates = (await (await page.request.get("/api/templates")).json()).templates as { id: string }[];

    // 3) Edit a template in the editor — add a shape and save.
    await page.goto(`/editor/${templates[0].id}`);
    await page.waitForFunction(() => !!(window as unknown as { __bnzCanvas?: unknown }).__bnzCanvas);
    await page.getByRole("button", { name: "Star", exact: true }).click();
    const saved = page.waitForResponse(
      (r) => r.url().includes("/api/templates/") && r.request().method() === "PUT" && r.ok(),
    );
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await saved;

    // 4) Use a template — create a usage and fill it in.
    await page.goto("/templates");
    await page.getByRole("button", { name: "Use this template" }).first().click();
    await page.getByRole("textbox", { name: "Name" }).fill("E2E journey usage");
    await page.getByRole("button", { name: "Create & fill in" }).click();
    await page.waitForURL("**/usages/**");

    const textField = page.locator('input[placeholder^="e.g."], input[placeholder^="Enter"]').first();
    if (await textField.count()) await textField.fill("Generated by an e2e journey");

    // Pick an image from the media library for the first image field.
    const library = page.getByRole("button", { name: "Library" }).first();
    if (await library.count()) {
      await library.click();
      await page.getByRole("button", { name: "Select" }).first().click();
      await expect(page.getByRole("button", { name: "Clear" }).first()).toBeVisible();
    }

    // 5) Trigger generation. We assert the render job is enqueued and enters its
    //    processing state — the full headless render completes in a production
    //    build (verified via docker compose); the in-process dev worker is too
    //    slow to reliably finish within a test, so we don't block on the image.
    await page.getByRole("button", { name: "Generate" }).click();
    await expect(page.getByText(/Rendering your image|Generating/i).first()).toBeVisible({ timeout: 20_000 });

    // 6) Admin page is reachable for this (admin) user.
    await page.goto("/admin");
    await expect(page.getByRole("heading", { name: "Reset application" })).toBeVisible();
  });
});
